/*
 * This file is generated by jOOQ.
 */
package com.danielkarpov.todo.model.Dao;


import com.danielkarpov.todo.model.Dao.tables.Task;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TASK_NAME_UINDEX = Indexes0.TASK_NAME_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index TASK_NAME_UINDEX = Internal.createIndex("task_name_uindex", Task.TASK, new OrderField[] { Task.TASK.NAME }, true);
    }
}
