/*
 * This file is generated by jOOQ.
 */
package com.danielkarpov.todo.model.Dao;


import com.danielkarpov.todo.model.Dao.tables.Task;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.Task</code>.
     */
    public static final Task TASK = Task.TASK;
}
